### ISSUE TITLE
Devices not shown on map

### ISSUE THREAD

**Issue by Akito13** [bfabiszewski/ulogger-server#97] opened 2019-09-26 12:59 UTC
The _track_ is visible on the web interface and the target user is also selectable from the drop down menu. The problem is that the selected user is not shown on the map, at all. Been testing for 24 hours now and it still does not show a single point where the user's device has been.

The client shows everything as _green_ and successfully sent.

**Comment by bfabiszewski** [comment] 2019-09-26 19:15
Closing as duplicate of #96

**Closed by bfabiszewski** 2019-09-26 19:15 UTC
Labels: duplicate
